site_name: YX的小站
theme:
  # name: readthedocs
  # name: mkdocs
  name: material
  favicon: images/ico/ico.jpg
  language: zh

  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到亮色模式

nav: 
  - Home:
      - Home: index.md
  
  - 自制工具集:
      - 自制工具集: SelfTools/index.md
      - 轻量化答题: SelfTools/answering_quiz.md

  - ROS2:
      - ROS2: ROS2/index.md
  
  - C++:
      - C++: C++/index.md
  
  - Python:
      - Python: Python/index.md

  - Linux:
      - Linux: Linux/index.md

  - LabVIEW:
      - LabVIEW: LabVIEW/index.md

  - 关于我: about.md


