site_name: YX的小站 # 网站名称
theme:  
  name: material  # 主题名称
  favicon: images/ico/ico.jpg # 网站图标
  language: zh  # 语言

  features: 
    - navigation.tabs # 选项卡导航
    - navigation.tabs.sticky  # 选项卡导航固定
    # - navigation.top  # 顶部导航
    - navigation.expand  # 导航栏展开
    - content.code.copy #代码复制

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到亮色模式

nav: 
  - Home:
    - Home: index.md

  - 自制工具集:
    - 概述: SelfTools/index.md
    - 答题系统: SelfTools/answering_quiz.md

  - ROS2:
      - ROS2: ROS2/index.md
      - Node: ROS2/Node.md
      - Topic: 
        - 概述: ROS2/Topic.md
        - 订阅: ROS2/Topic/Subscriber.md
        - 发布: ROS2/Topic/Publisher.md

      - Service: ROS2/Service.md
      - Action: ROS2/Action.md

  
  - C++:
      - C++: C++/index.md
      - C++基本语法: C++/C++基本语法.md
  
  - Python:
      - Python: Python/index.md

  - Linux:
      - Linux: Linux/index.md

  - LabVIEW:
      - LabVIEW: LabVIEW/index.md

  - 关于我: about.md



extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/489593500?spm_id_from=333.1007.0.0



extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
    - js/umlconvert.js

markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等

plugins:
  - search
  - mermaid2:
      version: 10.0.2


